# azure-pipelines.yml
# This pipeline builds and deploys the ASP.NET Core backend to Azure App Service

# Trigger the pipeline on pushes to the main branch
trigger:
- main

# Use a Microsoft-hosted agent VM image
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  azureAppName: 'webapi20250527115544'

# Define the steps for the pipeline
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
  displayName: 'Install .NET SDK'

- script: dotnet restore
  displayName: 'Restore Dependencies'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build .NET Project'

- script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) --no-build
  displayName: 'Publish .NET Project'

# Create web.config file
- powershell: |
    $content = '<?xml version="1.0" encoding="utf-8"?><configuration><location path="." inheritInChildApplications="false"><system.webServer><handlers><add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" /></handlers><aspNetCore processPath="dotnet" arguments=".\webapi.dll" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\stdout" hostingModel="inprocess" /></system.webServer></location></configuration>'
    Set-Content -Path "$(Build.ArtifactStagingDirectory)/web.config" -Value $content
  displayName: 'Create web.config'

# Create basic appsettings.json
- powershell: |
    $content = '{"Logging":{"LogLevel":{"Default":"Information","Microsoft.AspNetCore":"Warning"}},"AllowedHosts":"*"}'
    Set-Content -Path "$(Build.ArtifactStagingDirectory)/appsettings.json" -Value $content
  displayName: 'Create basic appsettings.json'

# Create publish artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'

# Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azureconnections'
    appType: 'webApp'
    appName: '$(azureAppName)'
    package: '$(Build.ArtifactStagingDirectory)'
    deploymentMethod: 'auto'
  displayName: 'Deploy to Azure App Service' 